// data.js - Sajeena Manzil Family Calendar Database
// AUTO-GENERATED BY sync.js - DO NOT EDIT MANUALLY

const BIRTHDAYS = [
  {
    "name": "Abdul Kalam",
    "month": 5,
    "day": 8
  },
  {
    "name": "Sajeena Abdul Kalam",
    "month": 5,
    "day": 16,
    "year": 1969
  },
  {
    "name": "Fathima Abdul Kalam",
    "month": 4,
    "day": 4
  },
  {
    "name": "Shaheen Sudheer",
    "month": 5,
    "day": 5
  },
  {
    "name": "Mohammad Samroud",
    "month": 4,
    "day": 8
  },
  {
    "name": "Hamsa Vellerkodath Bava",
    "month": 9,
    "day": 11,
    "year": 1969
  },
  {
    "name": "Haseena Hassan",
    "month": 10,
    "day": 27,
    "year": 1971
  },
  {
    "name": "Thanzeel Hassan",
    "month": 0,
    "day": 16,
    "year": 2000
  },
  {
    "name": "Mahra Hassan Vellerkodath",
    "month": 7,
    "day": 18,
    "year": 2004
  },
  {
    "name": "Abdul Nizar",
    "month": 1,
    "day": 13
  },
  {
    "name": "Sophia Nizar",
    "month": 3,
    "day": 16
  },
  {
    "name": "Ahsan Nizar",
    "month": 8,
    "day": 26
  },
  {
    "name": "Fathima Navas",
    "month": 6,
    "day": 2,
    "year": 2001
  },
  {
    "name": "Alia Abdul Nizar",
    "month": 7,
    "day": 14
  },
  {
    "name": "Abid Abdul Nizar",
    "month": 8,
    "day": 12
  },
  {
    "name": "Safeer Hassan Koya",
    "month": 10,
    "day": 20
  },
  {
    "name": "Shani Safeer",
    "month": 2,
    "day": 11
  },
  {
    "name": "Saad Safeer",
    "month": 7,
    "day": 24
  },
  {
    "name": "Salih Safeer",
    "month": 4,
    "day": 2
  },
  {
    "name": "Sameer Hassan Koya",
    "month": 3,
    "day": 6
  },
  {
    "name": "Nishi Sameer",
    "month": 6,
    "day": 27
  },
  {
    "name": "Fadhil Sameer",
    "month": 3,
    "day": 23
  },
  {
    "name": "Faiha Sameer",
    "month": 6,
    "day": 19
  },
  {
    "name": "Faheem Sameer",
    "month": 3,
    "day": 24
  },
  {
    "name": "Nizar Hassan Koya",
    "month": 8,
    "day": 7
  },
  {
    "name": "Muhsina Nizar",
    "month": 4,
    "day": 14
  },
  {
    "name": "Ihsan Nizar",
    "month": 11,
    "day": 12,
    "year": 2012
  },
  {
    "name": "Ifa Nizar",
    "month": 9,
    "day": 2
  },
  {
    "name": "Isha Nizar",
    "month": 0,
    "day": 6,
    "year": 2018
  },
  {
    "name": "Imran Nizar",
    "month": 11,
    "day": 2,
    "year": 2019
  }
];

const ANNIVERSARIES = [
  {
    "couple": "Hassan Koya and Sulaika Beevi",
    "month": 5,
    "day": 30,
    "generation": 1,
    "year": 1967
  },
  {
    "couple": "Sajeena Abdul Kalam and Abdul Kalam",
    "month": 8,
    "day": 29,
    "generation": 2,
    "year": 1992
  },
  {
    "couple": "Haseena Hassan and Hamsa Vellerkodath Bava",
    "month": 11,
    "day": 29,
    "generation": 2,
    "year": 1996
  },
  {
    "couple": "Sophia Nizar and Abdul Nizar",
    "month": 1,
    "day": 14,
    "generation": 2
  },
  {
    "couple": "Safeer Hassan Koya and Shani Safeer",
    "month": 2,
    "day": 27,
    "generation": 2
  },
  {
    "couple": "Sameer Hassan Koya and Nishi Sameer",
    "month": 6,
    "day": 13,
    "generation": 2
  },
  {
    "couple": "Nizar Hassan Koya and Muhsina Nizar",
    "month": 6,
    "day": 3,
    "generation": 2
  },
  {
    "couple": "Fathima Abdul Kalam and Shaheen Sudheer",
    "month": 6,
    "day": 9,
    "generation": 3,
    "year": 2023
  },
  {
    "couple": "Ahsan Nizar and Fathima Navas",
    "month": 6,
    "day": 29,
    "generation": 3,
    "year": 2024
  },
  {
    "couple": "Mohammad Samroud and Farsana",
    "month": 6,
    "day": 26,
    "generation": 3,
    "year": 2026
  }
];

// Helper variables for UI consumption
if (typeof exports !== 'undefined') {
  exports.BIRTHDAYS = BIRTHDAYS;
  exports.ANNIVERSARIES = ANNIVERSARIES;
}
