// data.js - Sajeena Manzil Family Calendar Database
// AUTO-GENERATED BY sync.js - DO NOT EDIT MANUALLY
// Edit the files in resources/ and run: node sync.js

const BIRTHDAYS = [
  {
    "name": "Abdul Kalam",
    "month": 5,
    "day": 8
  },
  {
    "name": "Sajeena Abdul Kalam",
    "month": 5,
    "day": 16,
    "year": 1969
  },
  {
    "name": "Fatima Abdul Kalam",
    "month": 4,
    "day": 4
  },
  {
    "name": "Shaheen Sudheer",
    "month": 5,
    "day": 5
  },
  {
    "name": "Mohamed Samroud",
    "month": 4,
    "day": 8
  },
  {
    "name": "Hamsa Vellerkodath Bava",
    "month": 10,
    "day": 11,
    "year": 1969
  },
  {
    "name": "Haseena Hassan",
    "month": 10,
    "day": 27,
    "year": 1971
  },
  {
    "name": "Thanzeel Hassan",
    "month": 0,
    "day": 16,
    "year": 2000
  },
  {
    "name": "Mahra Hassan Vellerkodath",
    "month": 7,
    "day": 18,
    "year": 2004
  },
  {
    "name": "Abdul Nizar",
    "month": 1,
    "day": 13
  },
  {
    "name": "Sophia Nizar",
    "month": 3,
    "day": 16
  },
  {
    "name": "Ahsan Nizar",
    "month": 8,
    "day": 26
  },
  {
    "name": "Fathima Navas",
    "month": 6,
    "day": 2,
    "year": 2001
  },
  {
    "name": "Alia Abdul Nizar",
    "month": 7,
    "day": 14
  },
  {
    "name": "Abid Abdul Nizar",
    "month": 8,
    "day": 12
  },
  {
    "name": "Safeer Hassan Koya",
    "month": 10,
    "day": 20
  },
  {
    "name": "Shani Safeer",
    "month": 2,
    "day": 12
  },
  {
    "name": "Saad Safeer",
    "month": 7,
    "day": 24
  },
  {
    "name": "Salih Safeer",
    "month": 4,
    "day": 2
  },
  {
    "name": "Sameer Hassan Koya",
    "month": 3,
    "day": 6
  },
  {
    "name": "Nishi Sameer",
    "month": 6,
    "day": 27
  },
  {
    "name": "Fadhil Sameer",
    "month": 3,
    "day": 23
  },
  {
    "name": "Faiha Sameer",
    "month": 6,
    "day": 19
  },
  {
    "name": "Faheem Sameer",
    "month": 3,
    "day": 24
  },
  {
    "name": "Nizar Hassan Koya",
    "month": 8,
    "day": 7
  },
  {
    "name": "Muhsina Nizar",
    "month": 4,
    "day": 14
  },
  {
    "name": "Ihsan Nizar",
    "month": 11,
    "day": 12,
    "year": 2012
  },
  {
    "name": "Ifa Nizar",
    "month": 9,
    "day": 2
  },
  {
    "name": "Isha Nizar",
    "month": 0,
    "day": 6,
    "year": 2018
  },
  {
    "name": "Imran Nizar",
    "month": 11,
    "day": 2,
    "year": 2019
  }
];

const ANNIVERSARIES = [
  {
    "couple": "Hassan Koya and Sulaika Beevi",
    "month": 5,
    "day": 30,
    "year": 1967,
    "generation": 1,
    "partners": [
      "Hassan Koya",
      "Sulaika Beevi"
    ]
  },
  {
    "couple": "Sajeena Abdul Kalam and Abdul Kalam",
    "month": 8,
    "day": 29,
    "year": 1992,
    "generation": 2,
    "partners": [
      "Sajeena Abdul Kalam",
      "Abdul Kalam"
    ]
  },
  {
    "couple": "Haseena Hassan and Hamsa Vellerkodath Bava",
    "month": 11,
    "day": 29,
    "year": 1996,
    "generation": 2,
    "partners": [
      "Haseena Hassan",
      "Hamsa Vellerkodath Bava"
    ]
  },
  {
    "couple": "Sophia Nizar and Abdul Nizar",
    "month": 1,
    "day": 14,
    "generation": 2,
    "partners": [
      "Sophia Nizar",
      "Abdul Nizar"
    ]
  },
  {
    "couple": "Safeer Hassan Koya and Shani Safeer",
    "month": 2,
    "day": 27,
    "generation": 2,
    "partners": [
      "Safeer Hassan Koya",
      "Shani Safeer"
    ]
  },
  {
    "couple": "Sameer Hassan Koya and Nishi Sameer",
    "month": 6,
    "day": 13,
    "generation": 2,
    "partners": [
      "Sameer Hassan Koya",
      "Nishi Sameer"
    ]
  },
  {
    "couple": "Nizar Hassan Koya and Muhsina Nizar",
    "month": 6,
    "day": 3,
    "generation": 2,
    "partners": [
      "Nizar Hassan Koya",
      "Muhsina Nizar"
    ]
  },
  {
    "couple": "Fatima Abdul Kalam and Shaheen Sudheer",
    "month": 6,
    "day": 9,
    "year": 2023,
    "generation": 3,
    "partners": [
      "Fatima Abdul Kalam",
      "Shaheen Sudheer"
    ]
  },
  {
    "couple": "Ahsan Nizar and Fathima Navas",
    "month": 6,
    "day": 29,
    "year": 2024,
    "generation": 3,
    "partners": [
      "Ahsan Nizar",
      "Fathima Navas"
    ]
  },
  {
    "couple": "Mohamed Samroud and Farsana",
    "month": 6,
    "day": 26,
    "year": 2026,
    "generation": 3,
    "partners": [
      "Mohamed Samroud",
      "Farsana"
    ]
  }
];

const FAMILY = [
  {
    "name": "Hassan Koya",
    "gender": "male",
    "generation": 1,
    "spouse": "Sulaika Beevi"
  },
  {
    "name": "Sulaika Beevi",
    "gender": "female",
    "generation": 1,
    "spouse": "Hassan Koya"
  },
  {
    "name": "Sajeena Abdul Kalam",
    "gender": "female",
    "generation": 2,
    "parents": [
      "Hassan Koya",
      "Sulaika Beevi"
    ],
    "spouse": "Abdul Kalam"
  },
  {
    "name": "Haseena Hassan",
    "gender": "female",
    "generation": 2,
    "parents": [
      "Hassan Koya",
      "Sulaika Beevi"
    ],
    "spouse": "Hamsa Vellerkodath Bava"
  },
  {
    "name": "Sophia Nizar",
    "gender": "female",
    "generation": 2,
    "parents": [
      "Hassan Koya",
      "Sulaika Beevi"
    ],
    "spouse": "Abdul Nizar"
  },
  {
    "name": "Safeer Hassan Koya",
    "gender": "male",
    "generation": 2,
    "parents": [
      "Hassan Koya",
      "Sulaika Beevi"
    ],
    "spouse": "Shani Safeer"
  },
  {
    "name": "Sameer Hassan Koya",
    "gender": "male",
    "generation": 2,
    "parents": [
      "Hassan Koya",
      "Sulaika Beevi"
    ],
    "spouse": "Nishi Sameer"
  },
  {
    "name": "Nizar Hassan Koya",
    "gender": "male",
    "generation": 2,
    "parents": [
      "Hassan Koya",
      "Sulaika Beevi"
    ],
    "spouse": "Muhsina Nizar"
  },
  {
    "name": "Abdul Kalam",
    "gender": "male",
    "generation": 2,
    "marriedIn": true,
    "spouse": "Sajeena Abdul Kalam"
  },
  {
    "name": "Hamsa Vellerkodath Bava",
    "gender": "male",
    "generation": 2,
    "marriedIn": true,
    "spouse": "Haseena Hassan"
  },
  {
    "name": "Abdul Nizar",
    "gender": "male",
    "generation": 2,
    "marriedIn": true,
    "spouse": "Sophia Nizar"
  },
  {
    "name": "Shani Safeer",
    "gender": "female",
    "generation": 2,
    "marriedIn": true,
    "spouse": "Safeer Hassan Koya"
  },
  {
    "name": "Nishi Sameer",
    "gender": "female",
    "generation": 2,
    "marriedIn": true,
    "spouse": "Sameer Hassan Koya"
  },
  {
    "name": "Muhsina Nizar",
    "gender": "female",
    "generation": 2,
    "marriedIn": true,
    "spouse": "Nizar Hassan Koya"
  },
  {
    "name": "Fatima Abdul Kalam",
    "gender": "female",
    "generation": 3,
    "parents": [
      "Abdul Kalam",
      "Sajeena Abdul Kalam"
    ],
    "spouse": "Shaheen Sudheer"
  },
  {
    "name": "Mohamed Samroud",
    "gender": "male",
    "generation": 3,
    "parents": [
      "Abdul Kalam",
      "Sajeena Abdul Kalam"
    ],
    "spouse": "Farsana"
  },
  {
    "name": "Ahsan Nizar",
    "gender": "male",
    "generation": 3,
    "parents": [
      "Abdul Nizar",
      "Sophia Nizar"
    ],
    "spouse": "Fathima Navas"
  },
  {
    "name": "Alia Abdul Nizar",
    "gender": "female",
    "generation": 3,
    "parents": [
      "Abdul Nizar",
      "Sophia Nizar"
    ]
  },
  {
    "name": "Abid Abdul Nizar",
    "gender": "male",
    "generation": 3,
    "parents": [
      "Abdul Nizar",
      "Sophia Nizar"
    ]
  },
  {
    "name": "Thanzeel Hassan",
    "gender": "male",
    "generation": 3,
    "parents": [
      "Hamsa Vellerkodath Bava",
      "Haseena Hassan"
    ]
  },
  {
    "name": "Mahra Hassan Vellerkodath",
    "gender": "female",
    "generation": 3,
    "parents": [
      "Hamsa Vellerkodath Bava",
      "Haseena Hassan"
    ]
  },
  {
    "name": "Saad Safeer",
    "gender": "male",
    "generation": 3,
    "parents": [
      "Safeer Hassan Koya",
      "Shani Safeer"
    ]
  },
  {
    "name": "Salih Safeer",
    "gender": "male",
    "generation": 3,
    "parents": [
      "Safeer Hassan Koya",
      "Shani Safeer"
    ]
  },
  {
    "name": "Fadhil Sameer",
    "gender": "male",
    "generation": 3,
    "parents": [
      "Sameer Hassan Koya",
      "Nishi Sameer"
    ]
  },
  {
    "name": "Faiha Sameer",
    "gender": "female",
    "generation": 3,
    "parents": [
      "Sameer Hassan Koya",
      "Nishi Sameer"
    ]
  },
  {
    "name": "Faheem Sameer",
    "gender": "male",
    "generation": 3,
    "parents": [
      "Sameer Hassan Koya",
      "Nishi Sameer"
    ]
  },
  {
    "name": "Ihsan Nizar",
    "gender": "male",
    "generation": 3,
    "parents": [
      "Nizar Hassan Koya",
      "Muhsina Nizar"
    ]
  },
  {
    "name": "Ifa Nizar",
    "gender": "female",
    "generation": 3,
    "parents": [
      "Nizar Hassan Koya",
      "Muhsina Nizar"
    ]
  },
  {
    "name": "Isha Nizar",
    "gender": "female",
    "generation": 3,
    "parents": [
      "Nizar Hassan Koya",
      "Muhsina Nizar"
    ]
  },
  {
    "name": "Imran Nizar",
    "gender": "male",
    "generation": 3,
    "parents": [
      "Nizar Hassan Koya",
      "Muhsina Nizar"
    ]
  },
  {
    "name": "Shaheen Sudheer",
    "gender": "male",
    "generation": 3,
    "marriedIn": true,
    "spouse": "Fatima Abdul Kalam"
  },
  {
    "name": "Fathima Navas",
    "gender": "female",
    "generation": 3,
    "marriedIn": true,
    "spouse": "Ahsan Nizar"
  },
  {
    "name": "Farsana",
    "gender": "female",
    "generation": 3,
    "marriedIn": true,
    "spouse": "Mohamed Samroud"
  }
];

// Helper variables for UI consumption
if (typeof exports !== 'undefined') {
  exports.BIRTHDAYS = BIRTHDAYS;
  exports.ANNIVERSARIES = ANNIVERSARIES;
  exports.FAMILY = FAMILY;
}
