// sync.js - Synchronize Sajeena Manzil Family Calendar Database
const fs = require('fs');

function parseMonth(monthName) {
    const months = {
        jan: 0, january: 0,
        feb: 1, february: 1,
        march: 2, mar: 2,
        apr: 3, april: 3,
        may: 4,
        jun: 5, june: 5,
        jul: 6, july: 6,
        aug: 7, august: 7,
        sep: 8, september: 8,
        oct: 9, october: 9,
        nov: 10, november: 10,
        dec: 11, december: 11
    };
    const key = monthName.toLowerCase().replace(/[^a-z]/g, '');
    if (months[key] !== undefined) return months[key];
    throw new Error(`Unknown month: ${monthName}`);
}

function parseBirthdays() {
    const content = fs.readFileSync('resources/Birthdays.txt', 'utf8');
    const lines = content.split('\n');
    const birthdays = [];

    for (let line of lines) {
        line = line.trim();
        if (!line || line.startsWith('Birthdays :')) continue;

        const parts = line.split('-');
        if (parts.length < 2) continue;

        const name = parts[0].trim();
        const dateStr = parts.slice(1).join('-').trim();

        // Replace commas and extra spaces
        const cleanDateStr = dateStr.replace(/,/g, ' ').replace(/\s+/g, ' ').trim();
        const dateParts = cleanDateStr.split(' ');

        if (dateParts.length < 2) {
            console.warn(`Skipping invalid birthday line: ${line}`);
            continue;
        }

        const month = parseMonth(dateParts[0]);
        const day = parseInt(dateParts[1], 10);

        const item = { name, month, day };

        if (dateParts.length >= 3) {
            const year = parseInt(dateParts[2], 10);
            if (!isNaN(year)) {
                item.year = year;
            }
        }

        birthdays.push(item);
    }
    return birthdays;
}

function parseAnniversaries() {
    const content = fs.readFileSync('resources/Wedding_anniversaries.txt', 'utf8');
    const lines = content.split('\n');
    const anniversaries = [];

    const coupleNameMap = {
        "Hassan Koya and Sulaika": "Hassan Koya and Sulaika Beevi",
        "Sajeena and Kalam": "Sajeena Abdul Kalam and Abdul Kalam",
        "Haseena and Hamsa": "Haseena Hassan and Hamsa Vellerkodath Bava",
        "Sophi and Nizar": "Sophia Nizar and Abdul Nizar",
        "Safeer and Shani": "Safeer Hassan Koya and Shani Safeer",
        "Sammer and Nishi": "Sameer Hassan Koya and Nishi Sameer",
        "Nizar and Muhsina": "Nizar Hassan Koya and Muhsina Nizar",
        "Fathima and Shaheen": "Fathima Abdul Kalam and Shaheen Sudheer",
        "Ahsan and Fathima": "Ahsan Nizar and Fathima Navas",
        "Samru and Farsana": "Mohammad Samroud and Farsana"
    };

    let currentGeneration = 1;

    for (let line of lines) {
        line = line.trim();
        if (!line || line.startsWith('Wedding anniversaries :')) continue;

        if (line.includes('1st gen')) {
            currentGeneration = 1;
            continue;
        }
        if (line.includes('2nd gen')) {
            currentGeneration = 2;
            continue;
        }
        if (line.includes('3rd gen')) {
            currentGeneration = 3;
            continue;
        }

        const parts = line.split('-');
        if (parts.length < 2) continue;

        const coupleRaw = parts[0].trim();
        const dateStr = parts.slice(1).join('-').trim();

        const couple = coupleNameMap[coupleRaw] || coupleRaw;

        // Remove "st", "nd", "rd", "th" from day values
        let cleanDateStr = dateStr.replace(/(\d+)(st|nd|rd|th)/gi, '$1');
        cleanDateStr = cleanDateStr.replace(/,/g, ' ').replace(/\s+/g, ' ').trim();
        const dateParts = cleanDateStr.split(' ');

        if (dateParts.length < 2) {
            console.warn(`Skipping invalid anniversary line: ${line}`);
            continue;
        }

        const month = parseMonth(dateParts[0]);
        const day = parseInt(dateParts[1], 10);

        const item = {
            couple,
            month,
            day,
            generation: currentGeneration
        };

        if (dateParts.length >= 3) {
            const year = parseInt(dateParts[2], 10);
            if (!isNaN(year)) {
                item.year = year;
            }
        }

        anniversaries.push(item);
    }
    return anniversaries;
}

function main() {
    try {
        const birthdays = parseBirthdays();
        const anniversaries = parseAnniversaries();

        const fileContent = `// data.js - Sajeena Manzil Family Calendar Database
// AUTO-GENERATED BY sync.js - DO NOT EDIT MANUALLY

const BIRTHDAYS = ${JSON.stringify(birthdays, null, 2)};

const ANNIVERSARIES = ${JSON.stringify(anniversaries, null, 2)};

// Helper variables for UI consumption
if (typeof exports !== 'undefined') {
  exports.BIRTHDAYS = BIRTHDAYS;
  exports.ANNIVERSARIES = ANNIVERSARIES;
}
`;

        fs.writeFileSync('data.js', fileContent, 'utf8');
        console.log('Successfully synchronized resources data to data.js!');
    } catch (err) {
        console.error('Error during synchronization:', err);
        process.exit(1);
    }
}

main();
